### ISSUE TITLE
Bug : portrait doesn't show up from printable stream

### ISSUE THREAD

**Issue by jbblily** [ShoyuVanilla/FoundryVTT-Chat-Portrait#33]
![image](https://user-images.githubusercontent.com/18694887/122677707-6d53ea80-d21e-11eb-8bad-72d16ffd9534.png)

I use printable stream module for chat log backup, but it seems that updated version of chat portrait disappears from printable stream...

**Comment by p4535992** [comment]
That module is very old. but i just tested with Chrome and foundry 0.8.7 and it's seem still working fine!
Have you tried to disable the other module (it's seem something Polygon can do) or if there is some exception on the browser console?

Anyway my suggestion is to use this module [DragonFlagon Chat Enhancements](https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-chat-enhance) for archive the chat log.

**Comment by p4535992** [comment]
Ok know i replicate the issue.
The solution is simple, there is no bug. The prinatble stream module get the content of the chat ad print on a file the source, but the module chat-portrait is a light solution and work hover the chat structure with just css and html.

There is no solution because there is no bug, like  i said you can just use the addon [DragonFlagon Chat Enhancements](https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-chat-enhance) for save the log.
