### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by Bryn1701** [ShoyuVanilla/FoundryVTT-Chat-Portrait#53]
When the chat window is full and a new message comes, regardless if its from an attack, a module system or simple a player message, the chat doesn't scroll all the way to the bottom and you have to keep dragging the scroll bar down to see the entire message in chat. I have tested it with no other modules enabled and it seems to persist. The only way I can stop it from doing this is to make Chrome full screen mode, and then it resolves the issue. I have tried zooming in and out in the browser to no avail. Screenshots for reference. 
https://gyazo.com/38a7318a2a73b1d5590f9bc3d970d26d 
https://gyazo.com/27ddba9e3552cf2c828f2e471ad300cb

Foundry 0.8.6
DND 5e 1.3.6
Chat Portrait 0.3.9

**Comment by psiondragon** [comment]
I am also having this problem. Foundry 8.x as well. I really enjoy being able to emote and the portrait shows, but not seeing what people chat (since they have to scroll a notch down each time) is a bit immersion-breaking.
Temporary solution for novices like us is to add padding to the CSS file, but unfortunately that adds gaps between all chat cards.

**Comment by p4535992** [comment]
Should be fixed 0.3.10

**Comment by psiondragon** [comment]
Thank you so much! It seems to be working!
