### ISSUE TITLE
Graphical bug when using Chat Portrait in Shadowrun 6 system

### ISSUE THREAD

**Issue by uetonm** [ShoyuVanilla/FoundryVTT-Chat-Portrait#76]
Your really great Chat Portrait module produces a graphical bug when used with the Shadworun 6 system ([](https://bitbucket.org/rpgframework-cloud/shadowrun6-eden/src/master)). Since the SR6 system is still in development, I am not sure if the bug has to be fixed in the SR6 system or the Chat Portrait module, but since there are much more modules than systems I think it makes sense to fix the module, if possible, so it works with all/most systems.

Now to the bug. The Shadowrun 6 system uses an icon (looks like a purple poker chip) when a player makes a test to show how much "Edge" a player has left. Without the module it looks like this:
![without_chat_portrait](https://user-images.githubusercontent.com/61244890/130155890-d3e89364-92f3-4eeb-97ae-170bef8ee30c.png)
The current number of Edge (here 3) is shown above the purple poker chip.

If you then enable the Chat Portrait module the Shadowrun icon gets misaligned (directly under the chat portrait) and it is also somehow on a layer above the chat messages (if you scroll the messages in the chat, the purple icon doesn't move). You can see the misalignment in my second screenshot:
![with_chat_portrait](https://user-images.githubusercontent.com/61244890/130156116-a2069a15-ae00-4ee9-918d-c9271d040c0f.png)

I hope you can fix it or maybe just some custom css code in the settings will suffice, i don't know.

**Comment by p4535992** [comment]
I will look into it.

**Comment by p4535992** [comment]
**IMPORTANT:** Since version 0.7.0, the module has been rewritten to allow for each system to have a css file to define the style and a description file of the mapping for the "ImageReplacer" feature.

Now the community can "come" to me a little, testing the css on their browser and help me understand which combination is the best, i file css si trovano nella directory degli [styles](https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/blob/master/src/styles), here a example for the [dnd5e system](https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/blob/master/src/styles/chat-portrait-style-dnd5e.css)
