### ISSUE TITLE
[BUG] Formatting bug on Skill Checks and Saving Throws

### ISSUE THREAD

**Issue by GambetTV** [ShoyuVanilla/FoundryVTT-Chat-Portrait#94]
When making a Skill Check or Saving Throw there is no break between the token name and the check result.

The formatting should look like:

Bob
Acrobatics Skill Check: Bob

Instead it looks like:

BobAcrobatics Skill Check: Bob

**Comment by p4535992** [comment]
can you provide some screenshot please ?

**Comment by GambetTV** [comment]
![image](https://user-images.githubusercontent.com/72000497/156405416-20f454b0-69b3-400b-b1ad-19741f113504.png)

**Comment by p4535992** [comment]
Maybe this issue is solved ?

**IMPORTANT:** Since version 0.7.0, the module has been rewritten to allow for each system to have a css file to define the style and a description file of the mapping for the "ImageReplacer" feature.

Now the community can "come" to me a little, testing the css on their browser and help me understand which combination is the best, i file css si trovano nella directory degli [styles](https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/blob/master/src/styles), here a example for the [dnd5e system](https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/blob/master/src/styles/chat-portrait-style-dnd5e.css)

**Comment by p4535992** [comment]
Try out 0.7.2 and let me know it

**Comment by GambetTV** [comment]
Apologies, I must have missed this months ago, but no, the issue continues to occur. I'm curious: Do you not see it on your end?
