### ISSUE TITLE
[BUG] Attack, saving throw and skill check card formatting broken in pf2e. 

### ISSUE THREAD

**Issue by Ghostdesu** [ShoyuVanilla/FoundryVTT-Chat-Portrait#98]
**Module Version:** v0.6.3

**Describe the bug**
Attack, saving throw and skill check cards have no formatting, all text elements appearing in a single line.

**To Reproduce**
1. Import a character from the Iconics compendium.
2. Roll an attack, skill check or saving throw. 

**Expected behavior**
The formatting should remain in line with vanilla pf2e system.

**Screenshots**
Normal cards without any modules
![image](https://user-images.githubusercontent.com/31375910/163052960-50eaa1eb-0466-4447-a92a-84acccd75323.png)
![image](https://user-images.githubusercontent.com/31375910/163052972-a61dae9c-26ee-4d13-84f6-84d40319085c.png)

Broken cards with Chat Portrait
![image](https://user-images.githubusercontent.com/31375910/163052844-8980c27e-f395-4e57-827e-3be238181a25.png)
![image](https://user-images.githubusercontent.com/31375910/163052860-5da48b11-3e79-457b-824f-08a9a05ba4c4.png)

**Browser:**
Firefox 99.0

**Foundry Version:** 
9.266

**Game System:** 
Pathfinder 2e 3.8.4.11118

**Additional context**
This issue did not appear until I updated from Chat Portrait 0.6.0

**Comment by p4535992** [comment]
I think i solbed this one?

**IMPORTANT:** Since version 0.7.0, the module has been rewritten to allow for each system to have a css file to define the style and a description file of the mapping for the "ImageReplacer" feature.

Now the community can "come" to me a little, testing the css on their browser and help me understand which combination is the best, i file css si trovano nella directory degli [styles](https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/blob/master/src/styles), here a example for the [dnd5e system](https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/blob/master/src/styles/chat-portrait-style-dnd5e.css)

**Comment by p4535992** [comment]
Try out 0.7.2 and let me know it

**Comment by Ghostdesu** [comment]
Yep, it all looks good now, thank you!
